import React, { useState, useEffect, useRef } from "react";
import { ToolProps } from "./ToolInterfaces";
import { useScript } from "./useScript";

// .gitignore templates dictionary
const GITIGNORE_TEMPLATES: Record<string, string> = {
  node: `# Logs\nlogs\n*.log\nnpm-debug.log*\n\n# Dependency directories\nnode_modules/\njspm_packages/\n\n# Optional npm cache directory\n.npm\n\n# Output directory\ndist/\nbuild/\n\n# Env files\n.env\n.env.local\n.env.production\n`,
  python: `# Byte-compiled / optimized / DLL files\n__pycache__/\n*.py[cod]\n*$py.class\n\n# Distribution / packaging\nbuild/\ndevelop-eggs/\ndist/\neggs/\nlib/\nlib64/\nparts/\nsdist/\nvar/\nwheels/\n*.egg-info/\n\n# Virtual environments\nvenv/\n.venv/\nenv/\n`,
  java: `# Compiled class file\n*.class\n\n# Log files\n*.log\n\n# BlueJ files\n*.ctxt\n\n# Mobile Tools for Java (J2ME)\n.mtj.tmp/\n\n# Package Files #\n*.jar\n*.war\n*.nar\n*.ear\n*.zip\n*.tar.gz\n*.rar\n\n# virtual machine crash logs\nhs_err_pid*\n`,
  react: `# production\n/build\n/dist\n\n# misc\n.DS_Store\n.env.local\n.env.development.local\n.env.test.local\n.env.production.local\n\nnpm-debug.log*\nyarn-debug.log*\nyarn-error.log*\n`,
  vue: `# Recommended gitignore for Vue.js\n/node_modules\n/dist\n\n# local env files\n.env.local\n.env.*.local\n\n# Log files\n*.log\n`,
  django: `*.log\n*.pot\n*.pyc\n__pycache__/\nlocal_settings.py\ndb.sqlite3\ndb.sqlite3-journal\nmedia/\n`,
  laravel: `/vendor/\nnode_modules/\npublic/storage\nHomestead.json\nHomestead.yaml\n.env\n`,
  go: `# Compiled Object files, local STDLIB\n*.o\n*.a\n*.so\n\n# Folders\n_obj\n_test\n\n# Architecture specific extensions\n*.5\n*.6\n*.8\n\n# Binary output\n*.exe\n*.test\n*.prof\n`,
  rust: `# Generated by Cargo\n# will have compiled files and executables\n/target/\n\n# Remove Cargo.lock from gitignore if building an executable\nCargo.lock\n\n# Backup files\n**/*.rs.bk\n`
};

// 29. QR Code Generator
export const QrCodeGenerator: React.FC<ToolProps> = ({ showToast }) => {
  const [text, setText] = useState("https://bytekit.dev");
  const qrRef = useRef<HTMLDivElement>(null);
  const qrStatus = useScript("https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js");

  useEffect(() => {
    if (qrStatus !== "ready" || !qrRef.current) return;
    
    // Clear previous QR code
    qrRef.current.innerHTML = "";
    
    const win = window as any;
    if (win.QRCode) {
      new win.QRCode(qrRef.current, {
        text: text,
        width: 160,
        height: 160,
        colorDark: "#2C2C2A",
        colorLight: "#FFFFFF",
      });
    }
  }, [text, qrStatus]);

  const handleDownload = () => {
    const img = qrRef.current?.querySelector("img");
    if (!img) {
      showToast("QR Code image not generated yet.");
      return;
    }

    const link = document.createElement("a");
    link.href = img.src;
    link.download = "qrcode.png";
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    showToast("Downloading QR Code PNG...");
  };

  return (
    <div className="tool-workspace">
      <div className="pane-container">
        <div className="pane">
          <label>Text or URL Input</label>
          <textarea
            value={text}
            onChange={(e) => setText(e.target.value)}
            placeholder="Type text or enter URL to generate QR code..."
            style={{ height: "140px" }}
          />
        </div>
        <div className="pane" style={{ alignItems: "center", justifyContent: "center", gap: "16px" }}>
          <label style={{ alignSelf: "flex-start" }}>QR Code Output</label>
          <div
            ref={qrRef}
            style={{
              padding: "16px",
              backgroundColor: "#FFFFFF",
              borderRadius: "10px",
              border: "1px solid var(--border)",
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              width: "192px",
              height: "192px"
            }}
          />
          <button className="btn btn-primary" onClick={handleDownload}>
            Download PNG
          </button>
        </div>
      </div>
    </div>
  );
};

// 30. .gitignore Generator
export const GitignoreGenerator: React.FC<ToolProps> = ({ showToast }) => {
  const [selected, setSelected] = useState<Record<string, boolean>>({
    node: true,
    react: true
  });
  const [output, setOutput] = useState("");

  const toggle = (key: string) => {
    setSelected((prev) => ({ ...prev, [key]: !prev[key] }));
  };

  const generate = () => {
    let result = `# Generated via ByteKit gitignore Generator\n\n`;
    Object.entries(selected).forEach(([key, val]) => {
      if (val && GITIGNORE_TEMPLATES[key]) {
        result += `### ${key.toUpperCase()} ###\n` + GITIGNORE_TEMPLATES[key] + `\n`;
      }
    });
    setOutput(result);
  };

  useEffect(() => {
    generate();
  }, [selected]);

  return (
    <div className="tool-workspace">
      <div className="pane-container">
        <div className="pane">
          <label>Select Technologies</label>
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "10px", padding: "8px 0" }}>
            {Object.keys(GITIGNORE_TEMPLATES).map((tech) => (
              <label key={tech} style={{ display: "flex", alignItems: "center", gap: "8px", cursor: "pointer", textTransform: "capitalize" }}>
                <input type="checkbox" checked={!!selected[tech]} onChange={() => toggle(tech)} />
                {tech}
              </label>
            ))}
          </div>
        </div>

        <div className="pane">
          <div style={{ display: "flex", justifySelf: "flex-end", justifyContent: "space-between", alignItems: "center", width: "100%" }}>
            <label>Generated .gitignore</label>
            <button className="btn btn-outline" onClick={() => {
              navigator.clipboard.writeText(output);
              showToast(".gitignore copied!");
            }} style={{ height: "30px" }}>Copy Code</button>
          </div>
          <textarea
            readOnly
            value={output}
            className="code-font"
            style={{ height: "260px", backgroundColor: "#1E1E2E", color: "#CDD6F4" }}
          />
        </div>
      </div>
    </div>
  );
};

// 31. Cron Expression Builder
export const CronBuilder: React.FC = () => {
  const [minute, setMinute] = useState("*");
  const [hour, setHour] = useState("*");
  const [day, setDay] = useState("*");
  const [month, setMonth] = useState("*");
  const [dayOfWeek, setDayOfWeek] = useState("*");

  const [description, setDescription] = useState("");
  const [runTimes, setRunTimes] = useState<string[]>([]);

  useEffect(() => {
    // Generate simple English description
    let desc = "Runs ";
    if (minute === "*" && hour === "*") desc += "every minute ";
    else if (minute !== "*" && hour === "*") desc += `at minute ${minute} of every hour `;
    else desc += `at ${hour.padStart(2, "0")}:${minute.padStart(2, "0")} `;

    if (day !== "*") desc += `on day of month ${day} `;
    if (month !== "*") desc += `in month ${month} `;
    if (dayOfWeek !== "*") {
      const days = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"];
      desc += `on ${days[Number(dayOfWeek)]} `;
    }

    setDescription(desc.trim() + ".");

    // Generate mock run times
    const times = [];
    let baseDate = new Date();
    for (let i = 0; i < 5; i++) {
      baseDate.setHours(baseDate.getHours() + (hour === "*" ? 1 : 24));
      times.push(baseDate.toLocaleString());
    }
    setRunTimes(times);
  }, [minute, hour, day, month, dayOfWeek]);

  return (
    <div className="tool-workspace">
      <div style={{ display: "grid", gridTemplateColumns: "repeat(5, 1fr)", gap: "10px" }}>
        <div className="form-group">
          <label>Minute</label>
          <select value={minute} onChange={(e) => setMinute(e.target.value)}>
            <option value="*">* (any)</option>
            {Array.from({ length: 60 }, (_, i) => (
              <option key={i} value={i.toString()}>{i}</option>
            ))}
          </select>
        </div>
        <div className="form-group">
          <label>Hour</label>
          <select value={hour} onChange={(e) => setHour(e.target.value)}>
            <option value="*">* (any)</option>
            {Array.from({ length: 24 }, (_, i) => (
              <option key={i} value={i.toString()}>{i}</option>
            ))}
          </select>
        </div>
        <div className="form-group">
          <label>Day</label>
          <select value={day} onChange={(e) => setDay(e.target.value)}>
            <option value="*">* (any)</option>
            {Array.from({ length: 31 }, (_, i) => (
              <option key={i + 1} value={(i + 1).toString()}>{i + 1}</option>
            ))}
          </select>
        </div>
        <div className="form-group">
          <label>Month</label>
          <select value={month} onChange={(e) => setMonth(e.target.value)}>
            <option value="*">* (any)</option>
            {Array.from({ length: 12 }, (_, i) => (
              <option key={i + 1} value={(i + 1).toString()}>{i + 1}</option>
            ))}
          </select>
        </div>
        <div className="form-group">
          <label>Day of Week</label>
          <select value={dayOfWeek} onChange={(e) => setDayOfWeek(e.target.value)}>
            <option value="*">* (any)</option>
            {["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"].map((d, idx) => (
              <option key={idx} value={idx.toString()}>{d}</option>
            ))}
          </select>
        </div>
      </div>

      <div style={{ padding: "16px", borderRadius: "8px", backgroundColor: "var(--primary-light)", border: "1px solid var(--primary)" }}>
        <strong>Cron Expression:</strong> <code className="code-font" style={{ fontSize: "16px", color: "var(--primary)" }}>{`${minute} ${hour} ${day} ${month} ${dayOfWeek}`}</code>
        <div style={{ marginTop: "6px", fontSize: "14px", color: "var(--text)" }}><strong>Meaning:</strong> {description}</div>
      </div>

      <div className="form-group">
        <label>Next 5 executions (approximate):</label>
        <ul style={{ listStyleType: "none", paddingLeft: 0 }}>
          {runTimes.map((t, idx) => (
            <li key={idx} className="code-font" style={{ fontSize: "13px", padding: "4px 8px", backgroundColor: "var(--bg)", borderBottom: "1px solid var(--border)" }}>
              {t}
            </li>
          ))}
        </ul>
      </div>
    </div>
  );
};

// Helper data for Fake Data
const NAMES = ["James Smith", "Michael Brown", "Emily Davis", "Sophia Wilson", "David Taylor", "Emma Thomas", "John Miller", "Olivia Anderson", "Chris Martin"];
const DOMAINS = ["gmail.com", "outlook.com", "bytekit.dev", "github.com", "google.com", "microsoft.com", "example.com"];
const CITIES = ["San Francisco, CA", "New York, NY", "Austin, TX", "Seattle, WA", "London, UK", "Berlin, DE", "Tokyo, JP"];

// 32. Fake Data Generator
export const FakeDataGenerator: React.FC<ToolProps> = ({ showToast }) => {
  const [count, setCount] = useState(5);
  const [type, setType] = useState<"name" | "email" | "phone" | "address" | "all">("all");
  const [output, setOutput] = useState("");

  const generateData = () => {
    const list = [];
    for (let i = 0; i < count; i++) {
      const id = i + 1;
      const name = NAMES[Math.floor(Math.random() * NAMES.length)];
      const email = name.toLowerCase().replace(" ", ".") + "@" + DOMAINS[Math.floor(Math.random() * DOMAINS.length)];
      const phone = `+1 (${Math.floor(Math.random() * 900) + 100}) 555-${Math.floor(Math.random() * 9000) + 1000}`;
      const address = `${Math.floor(Math.random() * 8999) + 1000} Main St, ` + CITIES[Math.floor(Math.random() * CITIES.length)];

      if (type === "name") list.push({ id, name });
      else if (type === "email") list.push({ id, email });
      else if (type === "phone") list.push({ id, phone });
      else if (type === "address") list.push({ id, address });
      else list.push({ id, name, email, phone, address });
    }
    setOutput(JSON.stringify(list, null, 2));
  };

  useEffect(() => {
    generateData();
  }, [count, type]);

  return (
    <div className="tool-workspace">
      <div className="form-row">
        <div className="form-group" style={{ flex: 1 }}>
          <label>Data Type</label>
          <select value={type} onChange={(e: any) => setType(e.target.value)}>
            <option value="all">Full Profile (All)</option>
            <option value="name">Names Only</option>
            <option value="email">Emails Only</option>
            <option value="phone">Phones Only</option>
            <option value="address">Addresses Only</option>
          </select>
        </div>
        <div className="form-group" style={{ flex: 1 }}>
          <label>Rows Count (1-50)</label>
          <input
            type="number"
            min="1"
            max="50"
            value={count}
            onChange={(e) => setCount(Math.min(50, Math.max(1, Number(e.target.value))))}
          />
        </div>
      </div>

      <div className="form-group">
        <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
          <label>Generated JSON Data</label>
          <button className="btn btn-outline" onClick={() => {
            navigator.clipboard.writeText(output);
            showToast("Dummy JSON copied!");
          }} style={{ height: "30px" }}>Copy JSON</button>
        </div>
        <textarea
          readOnly
          value={output}
          className="code-font"
          style={{ height: "220px", backgroundColor: "#1E1E2E", color: "#CDD6F4" }}
        />
      </div>
    </div>
  );
};

// 33. Meta Tag Generator
export const MetaTagGenerator: React.FC<ToolProps> = ({ showToast }) => {
  const [title, setTitle] = useState("ByteKit — Tools in the Browser");
  const [desc, setDesc] = useState("Free offline-ready, client-side tools for developers.");
  const [image, setImage] = useState("https://bytekit.dev/og-image.png");

  const tags = `<!-- HTML Primary Meta Tags -->
<title>${title}</title>
<meta name="title" content="${title}">
<meta name="description" content="${desc}">

<!-- Open Graph / Facebook -->
<meta property="og:type" content="website">
<meta property="og:url" content="https://bytekit.dev/">
<meta property="og:title" content="${title}">
<meta property="og:description" content="${desc}">
<meta property="og:image" content="${image}">

<!-- Twitter -->
<meta property="twitter:card" content="summary_large_image">
<meta property="twitter:url" content="https://bytekit.dev/">
<meta property="twitter:title" content="${title}">
<meta property="twitter:description" content="${desc}">
<meta property="twitter:image" content="${image}">`;

  return (
    <div className="tool-workspace">
      <div className="pane-container">
        <div className="pane" style={{ gap: "10px" }}>
          <div className="form-group" style={{ margin: 0 }}>
            <label>Page Title</label>
            <input type="text" value={title} onChange={(e) => setTitle(e.target.value)} />
          </div>
          <div className="form-group" style={{ margin: 0 }}>
            <label>Meta Description</label>
            <textarea value={desc} onChange={(e) => setDesc(e.target.value)} style={{ height: "80px", minHeight: "80px" }} />
          </div>
          <div className="form-group" style={{ margin: 0 }}>
            <label>OG Image URL</label>
            <input type="text" value={image} onChange={(e) => setImage(e.target.value)} />
          </div>
        </div>

        <div className="pane" style={{ justifyContent: "space-between" }}>
          <div>
            <label>Google Search Mockup</label>
            <div style={{ padding: "14px", backgroundColor: "#FFFFFF", border: "1px solid var(--border)", borderRadius: "8px", marginTop: "8px" }}>
              <div style={{ color: "#1a0dab", fontSize: "18px", textDecoration: "none", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" }}>{title}</div>
              <div style={{ color: "#006621", fontSize: "14px", marginTop: "2px" }}>https://bytekit.dev</div>
              <div style={{ color: "#545454", fontSize: "13px", marginTop: "4px", lineHeight: "1.4" }}>{desc}</div>
            </div>
          </div>

          <div className="form-group" style={{ margin: 0 }}>
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
              <label>Export HTML Tags</label>
              <button className="btn btn-primary" onClick={() => {
                navigator.clipboard.writeText(tags);
                showToast("HTML Meta Tags copied!");
              }} style={{ height: "30px" }}>Copy</button>
            </div>
            <textarea readOnly value={tags} className="code-font" style={{ height: "100px", minHeight: "100px", fontSize: "11px", backgroundColor: "#1E1E2E", color: "#CDD6F4" }} />
          </div>
        </div>
      </div>
    </div>
  );
};

// 34. SQL Formatter
export const SqlFormatter: React.FC<ToolProps> = ({ showToast }) => {
  const [input, setInput] = useState("select id, name, email from users where id > 10 group by id order by name desc;");
  const [output, setOutput] = useState("");

  const handleFormat = () => {
    if (!input.trim()) return;

    try {
      // Basic uppercase keywords and layout indent SQL mock
      const keywords = ["SELECT", "FROM", "WHERE", "JOIN", "ON", "AND", "OR", "GROUP BY", "ORDER BY", "INSERT", "INTO", "VALUES", "UPDATE", "SET", "LIMIT", "HAVING"];
      let formatted = input;
      
      keywords.forEach((keyword) => {
        const rx = new RegExp(`\\b${keyword}\\b`, "gi");
        formatted = formatted.replace(rx, `\n${keyword}`);
      });

      const lines = formatted
        .split("\n")
        .map((line) => line.trim())
        .filter((line) => line.length > 0)
        .map((line) => {
          // Add indentation for subqueries or fields
          if (!keywords.some((k) => line.toUpperCase().startsWith(k))) {
            return "  " + line;
          }
          return line;
        })
        .join("\n");

      setOutput(lines);
    } catch {
      showToast("Formatter failed!");
    }
  };

  return (
    <div className="tool-workspace">
      <div className="pane-container">
        <div className="pane">
          <label>Raw SQL</label>
          <textarea
            value={input}
            onChange={(e) => setInput(e.target.value)}
            placeholder="Paste your unformatted SQL query here..."
            className="code-font"
            style={{ height: "240px" }}
          />
          <button className="btn btn-primary" onClick={handleFormat}>
            Format SQL
          </button>
        </div>
        <div className="pane">
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
            <label>Beautified Query</label>
            {output && <button className="btn btn-outline" onClick={() => {
              navigator.clipboard.writeText(output);
              showToast("SQL query copied!");
            }} style={{ height: "30px" }}>Copy</button>}
          </div>
          <textarea readOnly value={output} className="code-font" style={{ height: "240px", backgroundColor: "#1E1E2E", color: "#CDD6F4" }} />
        </div>
      </div>
    </div>
  );
};
